version: "3"

services:
  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - MONGODB_HOST=<your-mongodb-hostname>
      - MONGODB_PORT=<your-mongodb-port>
      - MONGODB_USERNAME=<your-mongodb-username>
      - MONGODB_PASSWORD=<your-mongodb-password>
