available_text_models: ["gpt-4-1106-preview", "gpt-4-turbo", "gpt-4"]

info:
  gpt-4-turbo:
    type: chat_completion
    name: GPT-4 Turbo
    description: With 128k context, fresher knowledge and the broadest set of capabilities, GPT-4 Turbo is more powerful than GPT-4 and offered at a lower price.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2

  gpt-4:
    type: chat_completion
    name: GPT-4
    description: With broad general knowledge and domain expertise, GPT-4 can follow complex instructions in natural language and solve difficult problems with accuracy.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2

  gpt-4-1106-preview:
    type: chat_completion
    name: GPT-4 Turbo Preview
    description: GPT-4 Turbo Preview is a preview version of GPT-4 Turbo

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3

  gpt-4-vision-preview:
    type: chat_completion
    name: GPT-4 Vision
    description: Ability to <b>understand images</b>, in addition to all other GPT-4 Turbo capabilties.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3

  text-davinci-003:
    type: completion
    name: GPT-3.5
    description: GPT-3.5 is a legacy model. Actually there is <b>no reason to use it</b>, because it is more expensive and slower than ChatGPT, but just about as smart.

    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Smart: 3
      Fast: 2
      Cheap: 3

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006