available_text_models:
  [
    "gpt-3.5-turbo-1106",
    "gpt-3.5-turbo-0613",
    "gpt-3.5-turbo-16k-0613",
    "gpt-4-1106-preview",
    "gpt-4-vision-preview",
    "gpt-4-0613",
    "gpt-4-32k-0613",
  ]

info:
  gpt-3.5-turbo-1106:
    type: chat_completion
    name: GPT-3.5 Turbo 1106 (16K)
    description: GPT-3.5 Turbo models are capable and cost-effective. The most cost-effective model.

    price_per_1000_input_tokens: 0.001
    price_per_1000_output_tokens: 0.002

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-3.5-turbo-0613:
    type: chat_completion
    name: GPT-3.5 Turbo (4K)
    description: GPT-3.5 Turbo models are <b>capable</b> and <b>cost-effective</b>.

    price_per_1000_input_tokens: 0.0015
    price_per_1000_output_tokens: 0.002

    scores:
      Smart: 3
      Fast: 5
      Cheap: 4

  gpt-3.5-turbo-16k-0613:
    type: chat_completion
    name: GPT-3.5 Turbo (16k)
    description: GPT-3.5 Turbo models are <b>capable</b> and <b>cost-effective</b>.

    price_per_1000_input_tokens: 0.003
    price_per_1000_output_tokens: 0.004

    scores:
      Smart: 3
      Fast: 5
      Cheap: 4

  gpt-4-1106-preview:
    type: chat_completion
    name: GPT4 Turbo
    description: With 128k context, fresher knowledge and the broadest set of capabilities, GPT-4 Turbo is more powerful than GPT-4 and offered at a lower price.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      Smart: 5
      Fast: 3
      Cheap: 2

  gpt-4-vision-preview:
    type: chat_completion
    name: GPT-4 Turbo with vision
    description: With 128k context, fresher knowledge and the broadest set of capabilities, GPT-4 Turbo is more powerful than GPT-4 and offered at a lower price.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      Smart: 5
      Fast: 3
      Cheap: 2

  gpt-4-0613:
    type: chat_completion
    name: GPT4 (8K)
    description: With broad general knowledge and domain expertise, GPT-4 can follow complex instructions in natural language and solve difficult problems with accuracy.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 3
      Cheap: 1

  gpt-4-32k-0613:
    type: chat_completion
    name: GPT4 (32K)
    description: With broad general knowledge and domain expertise, GPT-4 can follow complex instructions in natural language and solve difficult problems with accuracy.

    price_per_1000_input_tokens: 0.06
    price_per_1000_output_tokens: 0.12

    scores:
      Smart: 5
      Fast: 3
      Cheap: 1

  dalle-2:
    type: image
    price_per_1_image: 0.018 # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006
